### DISCUSSION TITLE
RemixIcon For Flutter

### DISCUSSION THREAD

**Discussion by MzeeAlii** [Remix-Design/RemixIcon#543] [General]
Hello good people,

For anyone who is interested in this icon pack and would like to use it on Flutter projects, I coded a plugin to make RemixIcon pack easily available for Flutter apps.

> I even wrote a [piece on Medium](https://mzeealii.medium.com/remix-icon-for-developers-designers-c9687adf1f0e) about it.

### Installation

Add the `flutter_remix_icon` package to your project dependencies.

```yaml
# pubspec.yaml
dependencies:
    flutter_remix_icon:
        git:
          url: https://github.com/mzeealii/flutter-remix-icon.git

```

Run `pub get` to start using Remix Icon in your Flutter project.

### Using Icons

Import `flutter_remix_icon` package where you would like to use it.

```dart
import 'package:flutter_remix_icon/flutter_remix_icon.dart';

```

Get the icons by using `RemixIcon` class. Its static values return `IconData` which can be wrapped under widgets, such as `Icon`, to be customized and rendered on UI.

```dart
Icon(
  RemixIcon.flutter_fill,
  color: Theme.of(context).accentColor,
  size: 32,
);

```
